
interface _GlobalComponents {
      'AdminAddStudent': typeof import("../components/admin/AddStudent.vue")['default']
    'AdminAnnonce': typeof import("../components/admin/Annonce.vue")['default']
    'AdminEmploiAdd': typeof import("../components/admin/Emploi/Add.vue")['default']
    'AdminGroupsAdd': typeof import("../components/admin/Groups/Add.vue")['default']
    'AdminGroupsStudentList': typeof import("../components/admin/Groups/StudentList.vue")['default']
    'AdminPresence': typeof import("../components/admin/Presence.vue")['default']
    'AdminSearch': typeof import("../components/admin/Search.vue")['default']
    'AdminStudentAddingDoc': typeof import("../components/admin/Student/AddingDoc.vue")['default']
    'AdminStudentAddingPayment': typeof import("../components/admin/Student/AddingPayment.vue")['default']
    'AdminStudentAllInformation': typeof import("../components/admin/Student/AllInformation.vue")['default']
    'AdminStudentDocuments': typeof import("../components/admin/Student/Documents.vue")['default']
    'AdminStudentPaymentDetails': typeof import("../components/admin/Student/PaymentDetails.vue")['default']
    'AdminStudentPresence': typeof import("../components/admin/Student/Presence.vue")['default']
    'AdminStudentRemarques': typeof import("../components/admin/Student/Remarques.vue")['default']
    'AdminTable': typeof import("../components/admin/Table.vue")['default']
    'AdminTableActions': typeof import("../components/admin/Table/Actions.vue")['default']
    'AdminTableMessage': typeof import("../components/admin/Table/Message.vue")['default']
    'LayoutAlert': typeof import("../components/layout/Alert.vue")['default']
    'LayoutFooter': typeof import("../components/layout/Footer.vue")['default']
    'LayoutLoading': typeof import("../components/layout/Loading.vue")['default']
    'LayoutNavbar': typeof import("../components/layout/Navbar.vue")['default']
    'LayoutNoContent': typeof import("../components/layout/NoContent.vue")['default']
    'LayoutOtherNavbar': typeof import("../components/layout/OtherNavbar.vue")['default']
    'LayoutSecondLoading': typeof import("../components/layout/SecondLoading.vue")['default']
    'OwnerEtablissements': typeof import("../components/owner/Etablissements.vue")['default']
    'OwnerKpis': typeof import("../components/owner/Kpis.vue")['default']
    'StudentAnnonce': typeof import("../components/student/Annonce.vue")['default']
    'StudentInfo': typeof import("../components/student/Info.vue")['default']
    'StudentPaiements': typeof import("../components/student/Paiements.vue")['default']
    'StudentPresence': typeof import("../components/student/Presence.vue")['default']
    'StudentRemarque': typeof import("../components/student/Remarque.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'Icon': typeof import("../node_modules/nuxt-icon/dist/runtime/Icon.vue")['default']
    'IconCSS': typeof import("../node_modules/nuxt-icon/dist/runtime/IconCSS.vue")['default']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
      'LazyAdminAddStudent': typeof import("../components/admin/AddStudent.vue")['default']
    'LazyAdminAnnonce': typeof import("../components/admin/Annonce.vue")['default']
    'LazyAdminEmploiAdd': typeof import("../components/admin/Emploi/Add.vue")['default']
    'LazyAdminGroupsAdd': typeof import("../components/admin/Groups/Add.vue")['default']
    'LazyAdminGroupsStudentList': typeof import("../components/admin/Groups/StudentList.vue")['default']
    'LazyAdminPresence': typeof import("../components/admin/Presence.vue")['default']
    'LazyAdminSearch': typeof import("../components/admin/Search.vue")['default']
    'LazyAdminStudentAddingDoc': typeof import("../components/admin/Student/AddingDoc.vue")['default']
    'LazyAdminStudentAddingPayment': typeof import("../components/admin/Student/AddingPayment.vue")['default']
    'LazyAdminStudentAllInformation': typeof import("../components/admin/Student/AllInformation.vue")['default']
    'LazyAdminStudentDocuments': typeof import("../components/admin/Student/Documents.vue")['default']
    'LazyAdminStudentPaymentDetails': typeof import("../components/admin/Student/PaymentDetails.vue")['default']
    'LazyAdminStudentPresence': typeof import("../components/admin/Student/Presence.vue")['default']
    'LazyAdminStudentRemarques': typeof import("../components/admin/Student/Remarques.vue")['default']
    'LazyAdminTable': typeof import("../components/admin/Table.vue")['default']
    'LazyAdminTableActions': typeof import("../components/admin/Table/Actions.vue")['default']
    'LazyAdminTableMessage': typeof import("../components/admin/Table/Message.vue")['default']
    'LazyLayoutAlert': typeof import("../components/layout/Alert.vue")['default']
    'LazyLayoutFooter': typeof import("../components/layout/Footer.vue")['default']
    'LazyLayoutLoading': typeof import("../components/layout/Loading.vue")['default']
    'LazyLayoutNavbar': typeof import("../components/layout/Navbar.vue")['default']
    'LazyLayoutNoContent': typeof import("../components/layout/NoContent.vue")['default']
    'LazyLayoutOtherNavbar': typeof import("../components/layout/OtherNavbar.vue")['default']
    'LazyLayoutSecondLoading': typeof import("../components/layout/SecondLoading.vue")['default']
    'LazyOwnerEtablissements': typeof import("../components/owner/Etablissements.vue")['default']
    'LazyOwnerKpis': typeof import("../components/owner/Kpis.vue")['default']
    'LazyStudentAnnonce': typeof import("../components/student/Annonce.vue")['default']
    'LazyStudentInfo': typeof import("../components/student/Info.vue")['default']
    'LazyStudentPaiements': typeof import("../components/student/Paiements.vue")['default']
    'LazyStudentPresence': typeof import("../components/student/Presence.vue")['default']
    'LazyStudentRemarque': typeof import("../components/student/Remarque.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'LazyNuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LazyIcon': typeof import("../node_modules/nuxt-icon/dist/runtime/Icon.vue")['default']
    'LazyIconCSS': typeof import("../node_modules/nuxt-icon/dist/runtime/IconCSS.vue")['default']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
}

declare module '@vue/runtime-core' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module '@vue/runtime-dom' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const AdminAddStudent: typeof import("../components/admin/AddStudent.vue")['default']
export const AdminAnnonce: typeof import("../components/admin/Annonce.vue")['default']
export const AdminEmploiAdd: typeof import("../components/admin/Emploi/Add.vue")['default']
export const AdminGroupsAdd: typeof import("../components/admin/Groups/Add.vue")['default']
export const AdminGroupsStudentList: typeof import("../components/admin/Groups/StudentList.vue")['default']
export const AdminPresence: typeof import("../components/admin/Presence.vue")['default']
export const AdminSearch: typeof import("../components/admin/Search.vue")['default']
export const AdminStudentAddingDoc: typeof import("../components/admin/Student/AddingDoc.vue")['default']
export const AdminStudentAddingPayment: typeof import("../components/admin/Student/AddingPayment.vue")['default']
export const AdminStudentAllInformation: typeof import("../components/admin/Student/AllInformation.vue")['default']
export const AdminStudentDocuments: typeof import("../components/admin/Student/Documents.vue")['default']
export const AdminStudentPaymentDetails: typeof import("../components/admin/Student/PaymentDetails.vue")['default']
export const AdminStudentPresence: typeof import("../components/admin/Student/Presence.vue")['default']
export const AdminStudentRemarques: typeof import("../components/admin/Student/Remarques.vue")['default']
export const AdminTable: typeof import("../components/admin/Table.vue")['default']
export const AdminTableActions: typeof import("../components/admin/Table/Actions.vue")['default']
export const AdminTableMessage: typeof import("../components/admin/Table/Message.vue")['default']
export const LayoutAlert: typeof import("../components/layout/Alert.vue")['default']
export const LayoutFooter: typeof import("../components/layout/Footer.vue")['default']
export const LayoutLoading: typeof import("../components/layout/Loading.vue")['default']
export const LayoutNavbar: typeof import("../components/layout/Navbar.vue")['default']
export const LayoutNoContent: typeof import("../components/layout/NoContent.vue")['default']
export const LayoutOtherNavbar: typeof import("../components/layout/OtherNavbar.vue")['default']
export const LayoutSecondLoading: typeof import("../components/layout/SecondLoading.vue")['default']
export const OwnerEtablissements: typeof import("../components/owner/Etablissements.vue")['default']
export const OwnerKpis: typeof import("../components/owner/Kpis.vue")['default']
export const StudentAnnonce: typeof import("../components/student/Annonce.vue")['default']
export const StudentInfo: typeof import("../components/student/Info.vue")['default']
export const StudentPaiements: typeof import("../components/student/Paiements.vue")['default']
export const StudentPresence: typeof import("../components/student/Presence.vue")['default']
export const StudentRemarque: typeof import("../components/student/Remarque.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const Icon: typeof import("../node_modules/nuxt-icon/dist/runtime/Icon.vue")['default']
export const IconCSS: typeof import("../node_modules/nuxt-icon/dist/runtime/IconCSS.vue")['default']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyAdminAddStudent: typeof import("../components/admin/AddStudent.vue")['default']
export const LazyAdminAnnonce: typeof import("../components/admin/Annonce.vue")['default']
export const LazyAdminEmploiAdd: typeof import("../components/admin/Emploi/Add.vue")['default']
export const LazyAdminGroupsAdd: typeof import("../components/admin/Groups/Add.vue")['default']
export const LazyAdminGroupsStudentList: typeof import("../components/admin/Groups/StudentList.vue")['default']
export const LazyAdminPresence: typeof import("../components/admin/Presence.vue")['default']
export const LazyAdminSearch: typeof import("../components/admin/Search.vue")['default']
export const LazyAdminStudentAddingDoc: typeof import("../components/admin/Student/AddingDoc.vue")['default']
export const LazyAdminStudentAddingPayment: typeof import("../components/admin/Student/AddingPayment.vue")['default']
export const LazyAdminStudentAllInformation: typeof import("../components/admin/Student/AllInformation.vue")['default']
export const LazyAdminStudentDocuments: typeof import("../components/admin/Student/Documents.vue")['default']
export const LazyAdminStudentPaymentDetails: typeof import("../components/admin/Student/PaymentDetails.vue")['default']
export const LazyAdminStudentPresence: typeof import("../components/admin/Student/Presence.vue")['default']
export const LazyAdminStudentRemarques: typeof import("../components/admin/Student/Remarques.vue")['default']
export const LazyAdminTable: typeof import("../components/admin/Table.vue")['default']
export const LazyAdminTableActions: typeof import("../components/admin/Table/Actions.vue")['default']
export const LazyAdminTableMessage: typeof import("../components/admin/Table/Message.vue")['default']
export const LazyLayoutAlert: typeof import("../components/layout/Alert.vue")['default']
export const LazyLayoutFooter: typeof import("../components/layout/Footer.vue")['default']
export const LazyLayoutLoading: typeof import("../components/layout/Loading.vue")['default']
export const LazyLayoutNavbar: typeof import("../components/layout/Navbar.vue")['default']
export const LazyLayoutNoContent: typeof import("../components/layout/NoContent.vue")['default']
export const LazyLayoutOtherNavbar: typeof import("../components/layout/OtherNavbar.vue")['default']
export const LazyLayoutSecondLoading: typeof import("../components/layout/SecondLoading.vue")['default']
export const LazyOwnerEtablissements: typeof import("../components/owner/Etablissements.vue")['default']
export const LazyOwnerKpis: typeof import("../components/owner/Kpis.vue")['default']
export const LazyStudentAnnonce: typeof import("../components/student/Annonce.vue")['default']
export const LazyStudentInfo: typeof import("../components/student/Info.vue")['default']
export const LazyStudentPaiements: typeof import("../components/student/Paiements.vue")['default']
export const LazyStudentPresence: typeof import("../components/student/Presence.vue")['default']
export const LazyStudentRemarque: typeof import("../components/student/Remarque.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const LazyNuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LazyIcon: typeof import("../node_modules/nuxt-icon/dist/runtime/Icon.vue")['default']
export const LazyIconCSS: typeof import("../node_modules/nuxt-icon/dist/runtime/IconCSS.vue")['default']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']

export const componentNames: string[]
